# NumPy Arrays


### python objects:

    1. High-level number objects: integers, floating point
    2. containers: lists(costless insertion and append), dictionaries
    (fast lookup)

# NumPy provides

1.extension package to python for multi-dimensional arrays

2.closer to hardware(efficiency)

3.designed for scientific computation.

4.also known as array oriented computing

In [4]:
import numpy as np
a = np.array([0,2,4,6,8])
print(a)

print(a**2)

print(type(a))

print(np.arange(11))



[0 2 4 6 8]
[ 0  4 16 36 64]
<class 'numpy.ndarray'>
[ 0  1  2  3  4  5  6  7  8  9 10]



### why is it useful : 

Memory-efficient container that provides fast numerical operations

In [5]:
#python list
lst = range(1000)
%timeit [i**2 for i in lst]

259 µs ± 7.43 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
a = np.arange(1000) #numPy array
%timeit [a**2

1.25 µs ± 20.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


# CREATING ARRAYS

1.1 Manual construction of arays

1D Array -> vector

2D Array -> Matrix

nD Array -> Tensor

In [14]:
#1-D

a = np.array([0,1,2,3,4])

a

array([0, 1, 2, 3, 4])

In [15]:
#print dimension

a.ndim

1

In [16]:
#shape

a.shape

(5,)

In [18]:
#2D-3D ..

b = np.array([[0,2,4,], [1,3,5]])

b

array([[0, 2, 4],
       [1, 3, 5]])

In [19]:
b.ndim

2

In [21]:
b.shape  #rows, column

(2, 3)

In [22]:
len(b)  #returns the size of the first dimension (rows)

2

In [27]:
c = np.array([[2,4,6],[1,3,5],[8,10,12]]) #2D

c

array([[ 2,  4,  6],
       [ 1,  3,  5],
       [ 8, 10, 12]])

In [26]:
c.ndim

2

In [31]:
d = np.array([[[0,1],[2,3]], [[4,5] ,[6,7]]])
d

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [35]:
d.ndim

3

In [34]:
d.shape

(2, 2, 2)

# 1.2 Function for creating arrays

In [13]:
#using arange function

#arange is an array-valued version of the built-in Python range function

a = np.arange(10) #0 ... n-1

a

b = np.arange(10.)

b

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [45]:
b = np.arange(1, 10, 2) #start , end(exclusive), step
b

array([1, 3, 5, 7, 9])

In [47]:
#using linspace
a = np.linspace(0, 1, 6) #start , #end , #number of points

a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [48]:
#common arrays

a = np.ones((3,3)) 

a # 3*3 matrix of 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [50]:
b = np.zeros((3,2))

b

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [52]:
c = np.eye(3) #return 2-d array with ones on the diagonal and zeroes elsewhere

c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
d = np.eye(3,2) # no of rows = 3 and no of columns = 2
d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [3]:
#create array using diag function

a = np.diag([1,2,3,4]) #construct a diagonal array

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [4]:
np.diag(a) #extract diagonal

array([1, 2, 3, 4])

In [6]:
#create array using random

#create an array of the given shape and populate it with random sample from uniform distributed random number

a = np.random.rand(4) #np is package , #random - subpackage , rand - function  [returns an array of 4 elements]

a 

array([0.20342705, 0.90563714, 0.05322868, 0.34120071])

In [9]:
a = np.random.randn(4) #[randn-random normal]return a sample (or samples) from the "standard normal deviant"
 
a

array([ 0.20094472,  0.09903906, -0.63068225,  0.42073043])

# 2. BASIC DATA TYPES

you may have noticed that, ins ome instances , array elements are displayed with a trailing dot(eg, 2. vs 2) . This is due to a difference in the data-type used:

In [11]:
a = np.arange(10) #numpy array
 
print(a)

a.dtype

[0 1 2 3 4 5 6 7 8 9]


dtype('int32')

In [16]:
#you can explictily specify which data type you want:

a = np.arange(10, dtype = "float64")
a

a.dtype

dtype('float64')

In [17]:
#The default data type is float for zeroes and one function

a = np.zeros((2,3))

print(a)

a.dtype

[[0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

other datatypes:

In [19]:
d = np.array([1+2j , 2+4j]) #complex datatypes

print(d.dtype)

complex128


In [20]:
b = np.array([True, False , True , False])

print(b.dtype)

bool


In [27]:
s = np.array(["Hey, ", "I am", "ironman"])

s1 = np.array(['Malay' , ' Thakur'])
s.dtype
s1.dtype


dtype('<U7')

#### Each built-in data type has a character code tha uniquely identifies it.

'b' - boolean

'i' - signed(integer)

'u' - unsigned (integer)

'f' - floating point

'c' - complex floating point

'm' - timedelta

'M' - datetime

'O' - (Python) objects

'S' - 'a' - (byte-) string

'U' - Unicode

'V' - rawdata(void)

# 3. Indexing and Slicing

### 3.1 Indexing:

The items of an array can be accessed and assigned to the same way as other Python sequences (e.g.lists):


In [28]:
a = np.arange(10)

print(a[6]) #indices begin at 0 

6


In [29]:
#For multidimensional arrays , indexes are tuples of integers:
a = np.diag([1,2,3,4])

print(a[2,2]) #accessing element at 2nd row and 2 column

#remember, rows are identified as [a0 , a1 , a2]  and so columns are c0 , c1 , c2


3


In [30]:
a[2,1] = 5 #assigning value
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 5, 3, 0],
       [0, 0, 0, 4]])

## 3.2 slicing

In [3]:
a = np.arange(10)

a


NameError: name 'np' is not defined

In [33]:
a[0:10:2]  #startIndex : #endIndex : #step

array([0, 2, 4, 6, 8])

In [7]:
#we can also combine assignment and slicing:

a = np.arange(10)

a[5:] = 10

print(a)

print(a[::-1]) #reversing the array

[ 0  1  2  3  4 10 10 10 10 10]
[10 10 10 10 10  4  3  2  1  0]


In [9]:
b = np.arange(5)

a[5:] = b[::-1] #start #length #reverse(-1)  

print(a)

[0 1 2 3 4 4 3 2 1 0]


## 4. Copies and Views

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory . You can use np.may_share_memory() to check if two arrays share the same memory block.

#### when modifying the view, the original array is modified as well:

In [17]:
a = np.arange(11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
b = a[::2]
b

array([ 0,  2,  4,  6,  8, 10])

In [19]:
np.shares_memory(a,b) #this is view not copying

True

In [20]:
b[0] = 10
b

array([10,  2,  4,  6,  8, 10])

In [21]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
#eventhough we modified b, it updated 'a' cauz both share same memory location

In [22]:
a = np.arange(10)

c = a[::2].copy() #force a copy

c

array([0, 2, 4, 6, 8])

In [24]:
np.shares_memory(a,c)

False

In [25]:
c [0] = 10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 5. Fancy Indexing 

NumPy arrays can be indexed with slices, but also with boolean or integers arrays(masks).
This method is called fancy indexing. It creates copies not views.

#### using Boolean Mak

In [52]:
a = np.random.randint(0,20,15) #num>= 0 and num <20 i.e. range is (20) and 15 is the number of elements
a

array([14, 13, 16, 16, 18, 10,  9,  2, 19, 13,  8, 14,  8, 18,  5])

In [54]:
mask = (a%2==0) #returns the even num


In [55]:
extract_even = a[mask]

print(extract_even)



[14 16 16 18 10  2  8 14  8 18]


#### Indexing with a mask can be very useful to assign a new value to a sub-array:

In [56]:
a[mask] = -1 #puts -1 to all even numbers
print(a)

[-1 13 -1 -1 -1 -1  9 -1 19 13 -1 -1 -1 -1  5]


In [59]:
a = np.arange(0,100,10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [60]:
"""
indexing can be done with an array of integers, where the same index is 
repeated
"""
a[[2,3,2,4,2]]


array([20, 30, 20, 40, 20])

In [61]:
#New values can be assigned
a[[9,7]] = -69
a

array([  0,  10,  20,  30,  40,  50,  60, -69,  80, -69])